version: '3.5'


services:
  postgres:
    container_name: tdapostdb
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwd
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres-db:
    driver: local